[package]
name = "app"
version = "0.3.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos.workspace = true
leptos_meta.workspace = true
leptos_router.workspace = true
leptos_axum = { workspace = true, optional = true }
uuid.workspace = true

http.workspace = true
cfg-if.workspace = true
thiserror.workspace = true

serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
base64 = "0.22.1"
# sqlx 由 ssr feature 控制
sqlx = { workspace = true, optional = true }
chrono = { version = "0.4", features = ["serde"] }
# --- Client Side Dependencies ---
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    "HtmlCanvasElement",
    "HtmlImageElement",
    "CanvasRenderingContext2d",
    "AudioContext",
    "AnalyserNode",
    "MediaElementAudioSourceNode",
    "HtmlAudioElement",
    "HtmlMediaElement",
    "AudioDestinationNode",
    "Window",
    "Navigator",
    "Clipboard",
    "Location",
    "Document",
    "Element",
    "Node",
    "EventTarget",
    "HtmlInputElement",
    "FileList",
    "File",
    "FileReader",
    "Touch",
    "TouchEvent",
    "TouchList",
    "DomRect",
    "Event",
] }
anyhow = "1.0.100"
async-trait = "0.1.89"
email_address = "0.2.9"
phonenumber = "0.3.9"
sha2 = "0.10.9"

# wasm32 下 uuid(v4) 需要从浏览器获取随机数
[target.'cfg(target_arch = "wasm32")'.dependencies]
uuid = { workspace = true, features = ["js"] }


# --- 服务端依赖 (SSR) ---
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"
tokio-tungstenite = { version = "0.24", features = ["native-tls"] }
futures-util = "0.3"
bcrypt = "0.15"
# 新增：处理 Cookie
axum-extra = { version = "0.9", features = ["cookie"] }
time = "0.3"

[features]
default = []
hydrate = ["leptos/hydrate"]
ssr = [
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
    "dep:leptos_axum",
    "dep:sqlx",
]
